name: lxdmosaic
version: git
summary: Manage lxd
description: |
 yeah yeah
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

# Use a PPA to install a later version of sqlite3 than the default repo's provide
# See https://github.com/turtle0x1/LxdMosaic/issues/507 for details
# TODO Either compile sqlite3 ourselves or move to core20
package-repositories:
 - type: apt
   ppa: fbirlik/sqlite3


apps:
  # Apache daemon
  apache:
    command: run-httpd -k start -DFOREGROUND
    stop-command: httpd-wrapper -k stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

  # PHP FPM daemon
  php-fpm:
    command: start-php-fpm
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, removable-media, lxd]

  enable-https:
    command: enable-https
    plugs: [network, network-bind]

  disable-https:
    command: disable-https
    plugs: [network, network-bind]

  lxdmosaic-node:
    command: bin/node $SNAP/lxdmosaicNode/node/events.js
    daemon: simple
    plugs: [network, network-bind, lxd]

  lxdmosaic-cron:
    command: bin/bash $SNAP/htdocs/runCrunz.sh
    daemon: oneshot
    plugs: [network, network-bind, lxd]
    timer: 00:00-24:00/1440

hooks:
  configure:
    plugs: [network, network-bind]

parts:
  apache:
    plugin: apache
    source: https://dlcdn.apache.org/httpd/httpd-2.4.62.tar.bz2
    source-checksum: sha256/674188e7bf44ced82da8db522da946849e22080d73d16c93f7f4df89e25729ec

    override-pull: |
      snapcraftctl pull
      # For some reason, all directories in (and after) 2.4.32 are setgid.
      # Reported as https://bz.apache.org/bugzilla/show_bug.cgi?id=62298
      # Work around by unsetting setgid. FIXME: Remove when bug is fixed.
      find . -perm -g+s -exec chmod g-s {} \;

    # The built-in Apache modules to enable
    modules:
      - headers
      - proxy
      - proxy_fcgi
      - setenvif
      - env
      - rewrite
      - mime
      - dir
      - authz_core
      - unixd
      - alias
      - ssl
      - socache_shmcb
      - slotmem_shm
      - proxy_wstunnel
      - proxy_http
      - proxy_balancer

    filesets:
      exclude:
        - -man
        - -manual
        - -htdocs
        - -include
        - -build
        - -conf/httpd.conf
        - -conf/magic
        - -conf/original
        - -conf/extra
        - -bin/apachectl
        - -bin/envvars*
    stage:
      - $exclude
    prime:
      - $exclude

  apache-customizations:
    plugin: dump
    source: snap/local/apache/

  lxdmosaic-node:
    plugin: nodejs
    nodejs-version: "14.19.1"
    source: .
    organize:
      'LICENSE': 'madLadGoAway'
    override-build: |
      snapcraftctl build
      echo "Moving from $(pwd) to $SNAPCRAFT_PART_INSTALL/api..."
      mkdir -p $SNAPCRAFT_PART_INSTALL/lxdmosaicNode

      cp .env.dist .env

      sed -i "/CERT_PATH/c\CERT_PATH=\${SNAP_DATA}/certs/self-signed/cert.pem" .env
      sed -i "/CERT_PRIVATE_KEY/c\CERT_PRIVATE_KEY=\${SNAP_DATA}/certs/self-signed/privkey.pem" .env

      sed -i "/DB_SQLITE/c\DB_SQLITE=\${SNAP_DATA}/lxdMosaic.db" .env
      sed -i "/DB_HOST/c\DB_HOST=127.0.0.1" .env
      sed -i "/DB_USER/c\DB_USER=lxd" .env
      sed -i "/DB_PASS/c\DB_PASS=lxdManagerPasswordComplex321" .env
      sed -i "/DB_NAME/c\DB_NAME=LXD_Manager" .env
      sed -i "/LXD_CERTS_DIR/c\LXD_CERTS_DIR=\${SNAP_DATA}/" .env

      cat .env
      rm -rf LICENSE
      cp .env $SNAPCRAFT_PART_INSTALL/lxdmosaicNode/.env
      cp -R node/ $SNAPCRAFT_PART_INSTALL/lxdmosaicNode/
      cp -R node_modules/ $SNAPCRAFT_PART_INSTALL/lxdmosaicNode/

  lxdmosaic:
    plugin: dump
    source: .
    after: [php]
    organize:
      '*': htdocs/
    build-packages:
      - curl
      - php-cli
      - php-zip
      - rsync
      - unzip
    stage-packages:
      - bash
    override-pull: |
        snapcraftctl pull
        #Download composer
        curl -sS https://getcomposer.org/installer -o composer-setup.php
        ## Install it
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        composer install --ignore-platform-reqs
        # Dont know - dont care (conflicts with mysql license file ?)
        mv LICENSE LXD_MOSAIC_LICENSE
        rsync -arP * $SNAPCRAFT_STAGE/htdocs

  php:
    plugin: php
    source: https://php.net/get/php-7.4.11.tar.bz2/from/this/mirror
    source-checksum: sha256/5408f255243bd2292f3fbc2fafc27a2ec083fcd852902728f2ba9a3ea616b8c5
    source-type: tar
    install-via: prefix
    after: [apache]
    configflags:
      - --enable-fpm
      - --disable-cgi
      - --disable-phpdbg
      - --enable-ctype
      - --enable-mbstring
      - --with-zip
      - --with-pdo-mysql
      - --with-zlib
      - --enable-gd
      - --with-curl
      - --with-openssl
      - --with-bz2
      - --enable-exif
      - --enable-intl
      - --enable-pcntl
      - --with-jpeg
      - --with-freetype
      - --disable-rpath
      - --enable-ftp

      # Enable ldap
      - --with-libdir=lib/$SNAPCRAFT_ARCH_TRIPLET
      - --with-ldap

      # Enable gmp
      - --with-gmp
    build-packages:
      - apache2
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng-dev
      - libjpeg8-dev
      - libbz2-dev
      - libmcrypt-dev
      - libldap2-dev
      - libfreetype6-dev
      - libgmp-dev
      - libzip-dev
      - libargon2-0-dev
      - sqlite3
      - libsqlite3-dev

      # This is no longer bundled with PHP as of v7.4
      - libonig-dev
    stage-packages:
      - libasn1-8-heimdal
      - libcurl4
      - libfreetype6
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu60
      - libjpeg8
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpng16-16
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
      - libxml2
      - libzip4
      - libargon2-0
      - libonig4
      - sqlite3
      - libsqlite3-0
    prime:
     - -sbin/
     - -etc/
    organize:
      # Put php-fpm in bin with everything else, not sbin.
      sbin/php-fpm: bin/php-fpm

  # Copy over our PHP configuration file.
  php-customizations:
    plugin: dump
    source: snap/local/php/
    organize:
      config/*: config/php/
    stage-packages: [mawk]

  # Copy over our LxdMosaic configuration files
  lxdmosaic-customizations:
    plugin: dump
    source: snap/local/lxdmosaic/
    organize:
      config/.env: htdocs/.env

  delay-on-failure:
    plugin: dump
    source: snap/local/delay-on-failure/

  setup-https:
    plugin: dump
    source: snap/local/https/
    stage-packages: [openssl]
    stage: [-etc/ssl, -requirements.txt]

  common:
    plugin: dump
    source: snap/local/common/

  hooks:
    plugin: dump
    source: snap/local/hooks/
    organize:
      bin/: snap/hooks/
